[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "write", path = "./reports" }]
ffi = true
optimizer = true
optimizer_runs = 200
solc = '0.8.27'
evm_version = 'cancun'
bytecode_hash = 'none'
libraries = [
    'aave-v3-origin/contracts/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0xFeD9871528E713B5038c4c44BbE7a315f56cAdc6',
    'aave-v3-origin/contracts/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0x6E2aFD57a161d12f34f416c29619BFeAcAC8AA18',
    'aave-v3-origin/contracts/protocol/libraries/logic/EModeLogic.sol:EModeLogic:0xD1bddC05A3BB5A7907d82A1b4F1E21dBCE69c3d5',
    'aave-v3-origin/contracts/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0x5e84CEe2afb7B37d2AB14722C39A7c1C26F5B0BB',
    'aave-v3-origin/contracts/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0x36Ae486289bB807C3C79A1427b9c3D934294ef43',
    'aave-v3-origin/contracts/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0xE51B69e5722Bf547866A4d7Bc190c6e81b626806',
    'aave-v3-origin/contracts/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0x034Fd14b9Ae6bB066a1F9f85A55e990b0b25c168'
]

[profile.linea]
evm_version = 'london'
libraries = [
    'aave-v3-origin/contracts/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0x46464bCF5BBa29834b57E6c7631fEfb966F427A2',
    'aave-v3-origin/contracts/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0xD379a9e4A925916cF69c16C34409F401a28d5A52',
    'aave-v3-origin/contracts/protocol/libraries/logic/EModeLogic.sol:EModeLogic:0x9D147ED046EA1c629B6e66b0504E45019B133aa4',
    'aave-v3-origin/contracts/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0xb5656eCAE657A1bF5f7F5CD06363090A4D2c68e3',
    'aave-v3-origin/contracts/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0x22B38029a2B034340B695C6144B3AfD678e109E3',
    'aave-v3-origin/contracts/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0xbB6558a80Ed7811bd6d02bD26814e49c349b3acD',
    'aave-v3-origin/contracts/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0x330a2C27fCE66685d87ebaE4cE9dA71D2F6D1141'
]

[profile.zksync]
src = 'zksync'
test = 'zksync'
libs = ['lib']
solc = '0.8.27'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "write", path = "./reports" }]
ffi = true
evm_version = 'cancun'
libraries = [
    # TODO: update when v3.5 libraries will be deployed
    #'aave-v3-origin/contracts/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0x3db1dc584758daba133a59f776503b6c5d2dd1db',
    #'aave-v3-origin/contracts/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0x511eaFe32D70Aad1f0F87BAe560cbC2Ec88B34Db',
    #'aave-v3-origin/contracts/protocol/libraries/logic/EModeLogic.sol:EModeLogic:0xcdae69765333cae780e4bf6dcb7db886fae0b5a1',
    #'aave-v3-origin/contracts/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0xF8b48c00Ff12dD97F961EFE5240eBe956a3D8687',
    #'aave-v3-origin/contracts/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0x78ca5c313c8a3265a8bf69a645564181970be9c1',
    #'aave-v3-origin/contracts/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0x4511b06e1524929a4a90c5dd2aca59c8df728e8a',
    #'aave-v3-origin/contracts/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0x0095325bb5C5da5b19C92bb6919f80110dcbaEFF',
]

[profile.zksync.zksync]
bytecode_hash = 'none'
compile = true
fallback_oz = true
mode = '3'
zksolc = '1.5.13'

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
polygon = "${RPC_POLYGON}"
polygon_amoy = "${RPC_POLYGON_AMOY}"
avalanche = "${RPC_AVALANCHE}"
avalanche_fuji = "${RPC_AVALANCHE_FUJI}"
arbitrum = "${RPC_ARBITRUM}"
arbitrum_sepolia = "${RPC_ARBITRUM_SEPOLIA}"
fantom = "${RPC_FANTOM}"
fantom_testnet = "${RPC_FANTOM_TESTNET}"
optimism = "${RPC_OPTIMISM}"
optimism_sepolia = "${RPC_OPTIMISM_SEPOLIA}"
harmony = "${RPC_HARMONY}"
sepolia = "${RPC_SEPOLIA}"
scroll = "${RPC_SCROLL}"
scroll_sepolia = "${RPC_SCROLL_SEPOLIA}"
metis = "${RPC_METIS}"
base = "${RPC_BASE}"
base_sepolia = "${RPC_BASE_SEPOLIA}"
bnb = "${RPC_BNB}"
gnosis = "${RPC_GNOSIS}"
zkEVM = "${RPC_ZKEVM}"
celo = "${RPC_CELO}"
zksync = "${RPC_ZKSYNC}"
linea = "${RPC_LINEA}"
sonic = "${RPC_SONIC}"
soneium = "${RPC_SONEIUM}"

[fmt]
tab_width = 2
